[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=UTF-8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
